pluginManagement {
    repositories {
        mavenLocal()
        maven { url = "https://maven.fabricmc.net/" }
        gradlePluginPortal()
    }
}

if (file("Ponder").exists()) {
    includeBuild(".")
    includeBuild("Ponder") {
        dependencySubstitution {
            substitute(module("net.createmod.ponder:ponder-fabric")).using(project(":fabric"))
            substitute(module("net.createmod.ponder:ponder-common")).using(project(":common"))
        }
    }
}

rootProject.name = "$mod_id-fabric-$minecraft_version"
