#!/usr/bin/env python3
"""Generate src/main/resources/create.accesswidener from upstream's NeoForge accesstransformer.cfg.

The AT stays in the tree (excluded from the jar) so upstream changes to it merge cleanly;
re-run this script after merging. Field descriptors, which ATs omit, are read with javap from
Loom's mapped Minecraft jar, so run `./gradlew help` once first.

Mapping:
  public/protected field      -> accessible field
  public-f/protected-f field  -> accessible + mutable field
  public method               -> accessible method
  protected method            -> extendable method (stays protected, so Create's protected overrides still compile)
  *-f method                  -> also extendable (removes final so Create can override)
  public class                -> accessible class

Usage: scripts/fabric/at_to_aw.py [--jar path/to/minecraft-merged.jar] [--check]
"""

import glob
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
AT = REPO / "src/main/resources/META-INF/accesstransformer.cfg"
AW = REPO / "src/main/resources/create.accesswidener"
LOOM_JARS = "~/.gradle/caches/fabric-loom/minecraftMaven/net/minecraft/minecraft-merged/{mc}-loom.mappings.*layered*/minecraft-merged-*.jar"

ENTRY = re.compile(r"^(public|protected|private)(-f|\+f)?\s+(\S+)(?:\s+(\S+))?\s*(?:#.*)?$")


def minecraft_version() -> str:
	for line in (REPO / "gradle.properties").read_text().splitlines():
		if line.split("=")[0].strip() == "minecraft_version":
			return line.split("=", 1)[1].strip()
	raise SystemExit("minecraft_version not found in gradle.properties")


def find_jar(args: list[str]) -> str:
	if "--jar" in args:
		return args[args.index("--jar") + 1]
	jars = sorted(glob.glob(os.path.expanduser(LOOM_JARS.format(mc=minecraft_version()))), key=os.path.getmtime)
	# The parchment-layered jar is the one Create compiles against; any layered named jar has the same descriptors.
	if not jars:
		raise SystemExit("Mapped Minecraft jar not found; run ./gradlew help first, or pass --jar")
	return jars[-1]


_members: dict[str, tuple[dict[str, str], set[str]]] = {}


def members(jar: str, cls: str) -> tuple[dict[str, str], set[str]]:
	"""Returns ({field name: descriptor}, {method name + descriptor}) for a class."""
	if cls not in _members:
		result = subprocess.run(["javap", "-p", "-s", "-cp", jar, cls.replace("/", ".")], capture_output=True, text=True)
		if result.returncode != 0:
			raise SystemExit(f"Class {cls} not found in {jar}")
		out = result.stdout.splitlines()
		fields, methods = {}, set()
		for i, line in enumerate(out):
			if i + 1 >= len(out) or "descriptor:" not in out[i + 1]:
				continue
			desc = out[i + 1].split("descriptor:")[1].strip()
			if "(" in line:
				name = line[:line.index("(")].split()[-1].split(".")[-1]
				simple = cls.split("/")[-1].split("$")[-1]
				methods.add(("<init>" if name in (cls.replace("/", "."), simple) or name.endswith("$" + simple) else name) + desc)
			else:
				fields[line.rstrip(";").split()[-1]] = desc
		_members[cls] = (fields, methods)
	return _members[cls]


def convert(jar: str) -> list[str]:
	lines = ["accessWidener v2 named",
			 "# Generated by scripts/fabric/at_to_aw.py from META-INF/accesstransformer.cfg. Do not edit by hand;",
			 "# add Fabric-only entries to the AT with a '# fabric:' comment and re-run the script.",
			 ""]
	for raw in AT.read_text().splitlines():
		line = raw.strip()
		if not line:
			lines.append("")
			continue
		if line.startswith("#"):
			lines.append(line)
			continue
		m = ENTRY.match(line)
		if not m:
			raise SystemExit(f"Unrecognised AT line: {raw}")
		access, final_mod, cls, member = m.groups()
		if access == "private":
			raise SystemExit(f"Narrowing access isn't supported by access wideners: {raw}")
		cls = cls.replace(".", "/")
		remove_final = final_mod == "-f"

		if member is None:
			lines.append(f"accessible class {cls}")
			if remove_final:
				lines.append(f"extendable class {cls}")
		elif "(" in member:
			name, desc = member[:member.index("(")], member[member.index("("):]
			if name + desc not in members(jar, cls)[1]:
				lines.append(f"# not in {minecraft_version()}: {line}")
				continue
			# Protected methods stay protected: overrides in Create can't narrow a widened public method.
			if access == "public":
				lines.append(f"accessible method {cls} {name} {desc}")
			if remove_final or access == "protected":
				lines.append(f"extendable method {cls} {name} {desc}")
		else:
			desc = members(jar, cls)[0].get(member)
			if desc is None:
				lines.append(f"# not in {minecraft_version()}: {line}")
				continue
			lines.append(f"accessible field {cls} {member} {desc}")
			if remove_final:
				lines.append(f"mutable field {cls} {member} {desc}")

	# Collapse runs of blank lines left by the AT's grouping
	out = []
	for line in lines:
		if line == "" and out and out[-1] == "":
			continue
		out.append(line)
	return out


def main() -> int:
	args = sys.argv[1:]
	text = "\n".join(convert(find_jar(args))).rstrip() + "\n"
	if "--check" in args:
		if not AW.exists() or AW.read_text() != text:
			print(f"{AW.relative_to(REPO)} is out of date; run scripts/fabric/at_to_aw.py")
			return 1
		return 0
	AW.write_text(text)
	print(f"Wrote {AW.relative_to(REPO)} ({sum(1 for l in text.splitlines() if l and not l.startswith('#')) - 1} entries)")
	return 0


if __name__ == "__main__":
	sys.exit(main())
